[package]
name = "site-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
pulldown-cmark = "0.9.2"
tera = "1.17.1"
webbrowser = "0.8.0"

[dependencies.tokio]
version = "1.21.2"
features = ["full"]
