[package]
name = "site-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
pulldown-cmark = "*"
tera = "*"
webbrowser = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
